global:
  db:
    type: AZURESQL
  model:
    vllm: solidrust/Mistral-7B-Instruct-v0.3-AWQ
    embedding: sentence-transformers/distiluse-base-multilingual-cased
  storageClass: managed-csi

vllmServingRuntime:
  args:
    - "--model=/cache/models"
    - "--distributed-executor-backend=mp"
    - "--max-model-len=4096"
    - "--quantization=awq"
    - "--gpu-memory-utilization"
    - "0.98"
    - "--enforce-eager"

populateDbJob:
  repoSources:
    - repo: https://github.com/RHEcosystemAppEng/llm-on-openshift.git
      globs:
        - examples/notebooks/langchain/rhods-doc/*.pdf
  webSources:
    - https://ai-on-openshift.io/getting-started/openshift/
    - https://ai-on-openshift.io/getting-started/opendatahub/
    - https://ai-on-openshift.io/getting-started/openshift-ai/
    - https://ai-on-openshift.io/odh-rhoai/configuration/
    - https://ai-on-openshift.io/odh-rhoai/custom-notebooks/
    - https://ai-on-openshift.io/odh-rhoai/nvidia-gpus/
    - https://ai-on-openshift.io/odh-rhoai/custom-runtime-triton/
    - https://ai-on-openshift.io/odh-rhoai/openshift-group-management/
    - https://ai-on-openshift.io/tools-and-applications/minio/minio/
  chunking:
    size: 1024
    overlap: 40
