clusterGroup:
  namespaces:
    - azure-resources
    - cert-manager-operator:
        operatorGroup: true
        targetNamespaces: []

  subscriptions:
    cert-manager:
      name: cert-manager-operator
      namespace: cert-manager-operator
      channel: stable-v1

  projects:
    - azure-resources

  applications:
    azure-resources:
      name: azure-resources
      namespace: azure-resources
      project: azure-resources
      path: charts/all/azure-resources
