clusterGroup:
  namespaces:
    azure-resources

  project:
    azure-resources

  applications:
    azure-resources:
      name: azure-resources
      namespace: azure-service-operator
      project: azure-resources
      path: charts/all/azure-resources
