apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: ibm-granite-instruct
    serving.knative.openshift.io/enablePassthrough: 'true'
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  name: ibm-granite-instruct
  namespace: rag-llm
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    annotations:
      serving.knative.dev/progress-deadline: 30m
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '8'
          memory: 10Gi
          nvidia.com/gpu: '1'
        requests:
          cpu: '2'
          memory: 8Gi
          nvidia.com/gpu: '1'
      runtime: ibm-granite-instruct
    restartPolicy: OnFailure
    tolerations:
      - effect: NoSchedule
        key: odh-notebook
        operator: Exists