---
global:
  pattern: rag-llm-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  # Possible values for RAG vector DB db.type:
  #   REDIS     -> Redis (Local chart deploy)
  #   EDB       -> PGVector (Local chart deploy)
  #   MSSQL -> MS SQL Server (Local chart deploy)
  #   AZURESQL -> Azure SQL (Pre-existing in Azure)
  db:
    index: docs
    type: AZURESQL
  # Add for model ID
  model:
      modelId: ibm-granite/granite-3.1-8b-instruct
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
