---
global:
  pattern: rag-llm-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
  # Possible values for RAG vector DB db.type:
  #   REDIS     -> Redis (RediSearch)
  #   EDB       -> PGVector (PostgreSQL)
  #   SQLSERVER -> MS SQL Server (tech preview)
  db:
    index: docs
    type: REDIS
  # Add for model ID
  model:
      modelId: ibm-granite/granite-3.1-8b-instruct
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
