{{- if .Values.nvidia.driver.version }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-driver-repo-config
  namespace: nvidia-gpu-operator
data:
  repo: "nvcr.io/nvidia"
  image: "driver"
{{- end }}
