{{- if eq .Values.global.db.type "MSSQL" }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: mssql-external-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: mssql-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        CONNECTION_STRING: >
          Driver={{ printf "{%s}" .Values.driver }};
          Server={{ include "mssql.fullname" . }},{{ toString .Values.service.port }};
          Database={{ .Values.databaseName }};
          UID=sa;
          PWD={{ "{{ .sapass }}" }};
          TrustServerCertificate=yes;
          Encrypt=no;
        SA_PASSWORD: "{{ `{{ .sapass }}` }}"
  data:
  - secretKey: sapass
    remoteRef:
      key: {{ .Values.secretStore.mssqlSecretKey }}
      property: "sa-pass"
{{- end }}
