{{- if eq .Values.global.db.type "AZURESQL" }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: azuresql-external-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: azuresql-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        CONNECTION_STRING: >
          Driver={{ printf "{%s}" .Values.driver }};
          Server={{ "{{ .server }}" }},1433;
          Database={{ .Values.databaseName }};
          UID={{ "{{ .user }}" }};
          PWD={{ "{{ .password }}" }};
  data:
  - secretKey: user
    remoteRef:
      key: {{ .Values.secretStore.key }}
      property: "user"
  - secretKey: password
    remoteRef:
      key: {{ .Values.secretStore.key }}
      property: "password"
  - secretKey: server
    remoteRef:
      key: {{ .Values.secretStore.key }}
      property: "server"
{{- end }}
